CONFIG_LOG=y
CONFIG_USE_SEGGER_RTT=n
CONFIG_LOG_BACKEND_IPC_SERVICE=y
CONFIG_IPC_SERVICE=y
CONFIG_MBOX=y
CONFIG_PRINTK=n
CONFIG_BOOT_BANNER=n
CONFIG_IPC_SERVICE_BACKEND_ICMSG_ME_FOLLOWER=y

# Set to y to blast messages for stress testing
CONFIG_MOTION_IPC_STRESS_TEST=y

# I2C and Sensor subsystem
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_GPIO=y
CONFIG_LSM6DSL=y
CONFIG_LSM6DSL_TRIGGER_GLOBAL_THREAD=y
