
CONFIG_GPIO=y

# TM1640 Driver and PT18
CONFIG_TM1640=y
CONFIG_PT18_MATRIX=y
CONFIG_PT18_MATRIX_TEXT=y

# Console and RTT
CONFIG_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
