
CONFIG_GPIO=y

# TM1640 Driver and PT18
CONFIG_TM1640=y
CONFIG_PT18_MATRIX=y
CONFIG_PT18_MATRIX_TEXT=y

# Console and RTT
CONFIG_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# I2C and Sensor subsystem
CONFIG_I2C=y
CONFIG_SENSOR=y

# NAU7802 load cell driver
CONFIG_NAU7802_LOADCELL=y
CONFIG_NAU7802_LOADCELL_TRIGGER_GLOBAL_THREAD=y

# Float support for string formatting
CONFIG_CBPRINTF_FP_SUPPORT=y

# Disable default Zephyr coprocessor launcher
CONFIG_NORDIC_VPR_LAUNCHER=n

# Enable required RAM power management
CONFIG_RAM_POWER_DOWN_LIBRARY=y

# Bluetooth peripheral role used by SMP transport
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="SnailScale"

# MCUmgr / SMP server for OTA DFU
CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_TRANSPORT_BT_PERM_RW_AUTHEN=y
CONFIG_MCUMGR_TRANSPORT_BT_CONN_PARAM_CONTROL=y
CONFIG_MCUMGR_TRANSPORT_BT_REASSEMBLY=y
CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=1230
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_GRP_OS_BOOTLOADER_INFO=y
CONFIG_MCUMGR_GRP_OS_MCUMGR_PARAMS=y
CONFIG_MCUMGR_GRP_IMG=y

# tuning for BLE DFU
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

# Storage / image manager dependencies
CONFIG_CRC=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y

# ZMS requirements for RRAM
CONFIG_ZMS=y
CONFIG_SETTINGS_ZMS=y

CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_PROCESS_THREAD=y
CONFIG_LOG_MULTIDOMAIN=y
CONFIG_LOG_LINK_IPC_SERVICE=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_FAULT_DUMP=2
CONFIG_SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
CONFIG_SEGGER_RTT_MAX_NUM_UP_BUFFERS=2

CONFIG_IPC_SERVICE=y
CONFIG_MBOX=y