# MCUBOOT
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Disable NSIB
SB_CONFIG_SECURE_BOOT_APPCORE=n

# Overwriting instead of swapping
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y

# Skip signature verification
SB_CONFIG_BOOT_SIGNATURE_TYPE_NONE=y

# I know the migrating PM to DTS documentation says to use Kconfig, we are using an upstream board and not a custom one.
# This is a simpler fix, might have to go back and research it to make sure
SB_CONFIG_PARTITION_MANAGER=n