# MCUBOOT
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Disable NSIB
SB_CONFIG_SECURE_BOOT_APPCORE=n

# Overwriting instead of swapping
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y

# I know the migrating PM to DTS documentation says to use Kconfig, we are using an upstream board and not a custom one.
# This is a simpler fix, might have to go back and research it to make sure
SB_CONFIG_PARTITION_MANAGER=n

# generate dfu update package zip for nrf connect device manager
SB_CONFIG_DFU_ZIP=y
SB_CONFIG_DFU_ZIP_APP=y

# key pairing stuff
SB_CONFIG_BOOT_SIGNATURE_TYPE_ED25519=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_PURE=y
SB_CONFIG_MCUBOOT_SIGNATURE_USING_KMU=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APPLICATION_CONFIG_DIR}/keys/snailscale_ed25519_key.pem"