# SoftDevice multirole for nRF54LM20A
CONFIG_BT_LL_SOFTDEVICE_MULTIROLE=y

# ZMS cache optimization
CONFIG_ZMS_LOOKUP_CACHE=y
CONFIG_ZMS_LOOKUP_CACHE_SIZE=512
CONFIG_ZMS_LOOKUP_CACHE_FOR_SETTINGS=y

# Workaround as Zephyr L2 implies NVS backend for settings
CONFIG_NVS=n
