# Multirole is the only currently supported role by SoftDevice
CONFIG_BT_LL_SOFTDEVICE_MULTIROLE=y

# ZMS cache optimization
CONFIG_ZMS_LOOKUP_CACHE=y
CONFIG_ZMS_LOOKUP_CACHE_SIZE=512
CONFIG_ZMS_LOOKUP_CACHE_FOR_SETTINGS=y

# Workaround required as Zephyr L2 implies usage of NVS backend for settings
CONFIG_NVS=n
