import argparse
import os
import sys

def main():
    parser = argparse.ArgumentParser(description="Convert binary file to C header array")
    parser.add_argument("--input", required=True, help="Input binary file")
    parser.add_argument("--output", required=True, help="Output C header file")
    parser.add_argument("--array-name", required=True, help="Name of the generated C array")
    
    args = parser.parse_args()
    
    in_file = args.input
    out_file = args.output
    array_name = args.array_name
    
    if not os.path.exists(in_file):
        print(f"Error: {in_file} not found")
        sys.exit(1)
        
    with open(in_file, "rb") as f:
        data = f.read()
        
    with open(out_file, "w") as f:
        f.write("/* Auto-generated by bin_to_header.py */\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define {array_name.upper()}_SIZE {len(data)}\n\n")
        f.write(f"const uint8_t {array_name}[] __attribute__((aligned(4))) = {{\n")
        
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            f.write("    " + ", ".join([f"0x{b:02x}" for b in chunk]))
            if i + 16 < len(data):
                f.write(",")
            f.write("\n")
            
        f.write("};\n")

if __name__ == "__main__":
    main()
