import sys
import os

def main():
    if len(sys.argv) != 3:
        print("Usage: python bin_to_header.py <input.bin> <output.h>")
        sys.exit(1)
        
    in_file = sys.argv[1]
    out_file = sys.argv[2]
    
    if not os.path.exists(in_file):
        print(f"Error: {in_file} not found")
        sys.exit(1)
        
    with open(in_file, "rb") as f:
        data = f.read()
        
    with open(out_file, "w") as f:
        f.write("/* Auto-generated by bin_to_header.py */\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define FLPR_FIRMWARE_SIZE {len(data)}\n\n")
        f.write("const uint8_t flpr_firmware[] __attribute__((aligned(4))) = {\n")
        
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            f.write("    " + ", ".join([f"0x{b:02x}" for b in chunk]))
            if i + 16 < len(data):
                f.write(",")
            f.write("\n")
            
        f.write("};\n")

if __name__ == "__main__":
    main()
